version: 1

policy:
  default:
    min: 80

  domains:
    # Core domains - high coverage required
    - name: config
      match: ["./internal/domain/config/..."]
      min: 70  # Core configuration domain (hooks/lifecycle have external deps)

    - name: compiler
      match: ["./internal/domain/compiler/..."]
      min: 85  # Critical compilation logic

    - name: execution
      match: ["./internal/domain/execution/..."]
      min: 90  # Critical execution logic

    # Provider layer - external system integration
    - name: providers
      match: ["./internal/provider/..."]
      min: 78  # External system adapters (aggregate coverpkg varies by Go version)

    # Application layer
    - name: app
      match: ["./internal/app/..."]
      min: 43  # External commands untestable (vscode, mise, asdf, GitHub API, fleet sync)

    - name: cli
      match: ["./cmd/..."]
      min: 32  # TUI/interactive commands and external tool calls (brew, grype) vary by environment

    # Platform & infrastructure
    - name: platform
      match: ["./internal/domain/platform/..."]
      min: 45  # Requires actual WSL/Docker environment

    - name: marketplace
      match: ["./internal/domain/marketplace/..."]
      min: 75  # HTTP-dependent code paths

    # Security domains - high coverage required
    - name: audit
      match: ["./internal/domain/audit/..."]
      min: 55  # Security audit logging (isolated: 90%, cumulative lower until integrated)

exclude:
  - "internal/generated/*"
  - "**/*_test.go"
