version: 1

policy:
  default:
    min: 80

  domains:
    - name: config
      match: ["./internal/domain/config/..."]
      min: 80

    - name: compiler
      match: ["./internal/domain/compiler/..."]
      min: 80

    - name: execution
      match: ["./internal/domain/execution/..."]
      min: 80

    - name: providers
      match: ["./internal/provider/..."]
      min: 80

    - name: app
      match: ["./internal/app/..."]
      min: 53  # Lowered from 70%: remaining untested code requires external commands (vscode, mise, asdf) or GitHub auth

    - name: cli
      match: ["./cmd/..."]
      min: 52  # Lowered from 58%: CI environment has lower coverage due to skipped tests

exclude:
  - "internal/generated/*"
  - "**/*_test.go"
