version: 1

policy:
  default:
    min: 80

  domains:
    - name: config
      match: ["./internal/domain/config/..."]
      min: 80

    - name: compiler
      match: ["./internal/domain/compiler/..."]
      min: 80

    - name: execution
      match: ["./internal/domain/execution/..."]
      min: 80

    - name: providers
      match: ["./internal/provider/..."]
      min: 80

    - name: app
      match: ["./internal/app/..."]
      min: 53  # Lowered from 70%: remaining untested code requires external commands (vscode, mise, asdf) or GitHub auth

    - name: cli
      match: ["./cmd/..."]
      min: 42  # CLI threshold: TUI commands (capture, doctor, rollback, discover) require integration tests

    - name: platform
      match: ["./internal/domain/platform/..."]
      min: 45  # Platform-specific: WSL/Docker detection functions require actual WSL/Docker environment

    - name: marketplace
      match: ["./internal/domain/marketplace/..."]
      min: 76  # Community features: some HTTP-dependent code paths

exclude:
  - "internal/generated/*"
  - "**/*_test.go"
