version: 2

project_name: preflight

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: preflight
    main: ./cmd/preflight
    binary: preflight
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: felixgeelhaar
    name: preflight
  draft: false
  prerelease: auto
  make_latest: true
  name_template: "v{{.Version}}"

brews:
  - name: preflight
    repository:
      owner: felixgeelhaar
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/felixgeelhaar/preflight"
    description: "Deterministic workstation compiler"
    license: "MIT"
    test: |
      system "#{bin}/preflight", "version"
    install: |
      bin.install "preflight"

changelog:
  disable: true  # We use relicta for changelogs
